# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#Environment variables
env:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS: "4333796"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name : Run before
        run: wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  
      - name: unzip
        run: unzip -d android-sdk-linux android-sdk.zip
      
      - name: set sdkmanager 1
        run: echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
        
      - name: set sdkmanager 2
        run: echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
        
      - name: set build tools
        run: echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
        
      - name: export pwd
        run: export ANDROID_HOME=$PWD/android-sdk-linux
    
      - name: export path
        run: export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: run test
        run: ./gradlew test
        
      - name: Build with Gradle
        run: ./gradlew build
